### ISSUE TITLE
client-only mods in server

### ISSUE THREAD

**Issue by willis936** [GregTechCEu/GregTech-Community-Pack#77]
Please remove these client-only mods from the server archive:

- BetterAdvancements-1.12.2-0.1.0.77.jar
- BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
- ClientTweaks_1.12.2-3.1.11.jar
- Controlling-3.0.10.jar
- CosmeticArmorReworked-1.12.2-v5a.jar
- CraftingTweaks_1.12.2-9.0.1.jar
- CTM-MC1.12.2-1.0.2.31.jar
- Ding-1.12.2-1.0.2.jar
- dynamistics-1.0.2.jar
- EnchantmentDescriptions-1.12.2-1.1.20.jar
- jeiintegration_1.12.2-1.6.0.jar
- modnametooltip_1.12.2-1.10.1.jar
- moreoverlays-1.15.1-mc1.12.2.jar
- MouseTweaks-3.1.2-mc1.12.2.jar
- oauth-1.06.4.jar
- overloadedarmorbar-1.0.4g.jar
- ResourceLoader-MC1.12.1-1.5.3.jar
- TipTheScales-1.12.2-1.0.4.jar
- Toast\ Control-1.12.2-1.8.1.jar
- moresoundconfig-1.0.4.jar

**Comment by willis936** [comment]
Correction: `CosmeticArmorReworked-1.12.2-v5a.jar` is a dependency for TombManyPlugins and still needs to be present.

**Comment by willis936** [comment]
I ran this command in my mods folder (sharing for ease of later use), started the server, and was able to connect.

`sudo rm BetterAdvancements-1.12.2-0.1.0.77.jar BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar ClientTweaks_1.12.2-3.1.11.jar Controlling-3.0.10.jar CraftingTweaks_1.12.2-9.0.1.jar CTM-MC1.12.2-1.0.2.31.jar Ding-1.12.2-1.0.2.jar dynamistics-1.0.2.jar EnchantmentDescriptions-1.12.2-1.1.20.jar jeiintegration_1.12.2-1.6.0.jar modnametooltip_1.12.2-1.10.1.jar moreoverlays-1.15.1-mc1.12.2.jar MouseTweaks-3.1.2-mc1.12.2.jar oauth-1.06.4.jar overloadedarmorbar-1.0.4g.jar ResourceLoader-MC1.12.1-1.5.3.jar TipTheScales-1.12.2-1.0.4.jar Toast\ Control-1.12.2-1.8.1.jar moresoundconfig-1.0.4.jar`

**Comment by TechLord22** [comment]
The mods marked as ClientSideOnly in code will be skipped in the loading process by forge. This was set for all of those mods except for MoreOverlays and two others. Regardless of this, I'm working on removing these mods from the server build.

Also to note, BetterBuildersWands is required on the server, since it adds items. Dan's Mouse Tweaks also has additional functionality when installed on the server as well. These two should not cause issues if present. If re-adding the two to your server causes an error, it would be very helpful if you could send the crash report or the latest.log file.

**Comment by willis936** [comment]
I've added BetterBuildersWands and MouseTweaks back in and will test during a reboot in a few hours.

The list above is from FML log output identifying mods as client only and not loading them.  I didn't run into FML warning about missing blocks when I removed that full list of mods and booted the server with an existing world.

**Comment by willis936** [comment]
I can confirm that BetterBuildersWands and MouseTweaks load in and FML did not complain.
